### ISSUE TITLE
Clicking on monster portrait doesn't choose the most experienced one  

### ISSUE THREAD

**Issue by eraser2011** [Loobinex/keeperfx-unofficial#1]
In the original DK version, it was possible to get the highest level monster with one click on the according portrait. It doesn't seem to be working in the latest keeperfx version. It was a very useful future, it would be great to have it again!

**Comment by Loobinex** [comment]
I know, I preferred the original behavior as well. Or to at least be consistent.
The issue has been reported several times on KeeperFX though, see [Issue 222](https://github.com/dkfans/keeperfx/issues/222). It is not something I introduced in the unofficial release.

I did take a quick look, but it was not an easy fix for me. However, if you know what changes to make to the source, feel free to share.

And finally, know that you can pickup the Highest level creature with 'Ctrl+click'.

**Comment by eraser2011** [comment]
Alright, good to know! "ctrl+click" seems to be an okish workaround. I searched in the source code, but couldn't find something helpful. Thanks Loobinex for the fast help :)

**Comment by Loobinex** [comment]
The relevant code is located from line 1305 onward in [frontmenu_ingame_tabs.c](https://github.com/dkfans/keeperfx-stable/blob/6f2f204f2b0087b183f515920983af73ba164944/src/frontmenu_ingame_tabs.c)

**Comment by Loobinex** [comment]
I've looked into this some more, and it is to complicated for me to improve the behavior.
