### ISSUE TITLE
Game closes / crashes on level start

### ISSUE THREAD

**Issue by Ccursed** [Loobinex/keeperfx-unofficial#129]
Hello,

I recently played the third level of the original campaign, at some point I clicked on the map and after leaving it, my "camera orientation" was shifted, from the slightly rotated view to the straight view. After attempting to change it back via the ESC menu, my game crashed. 

Now upon trying to start any new map (campaign or free play), the level loads, I get the camera motion through the dungeon heart and then the game crashes.

Log file: 

> Dungeon Keeper FX ver 0.4.7u build 1913 (standard release)
> LOG CREATED  @ 07:03:13  22-02-2020
> 
> Sync: LbMouseChangeMoveRatio: New ratio 256x256
> Sync: CPU GenuineIntel type 0 family 6 model 14 stepping 1 features bfebfbff
> Sync: PhysicalMemory 32
> Sync: Memory-demanding features enabled.
> Sync: LbScreenSetup: Mode 2560x1440x32 setup succeeded
> Sync: Moon phase 0.8212
> Warning: Sound system disabled.
> LbDataFree: freeing "*PALETTE"...done
> LbDataFree: freeing "*SCRATCH"...done
> Sync: LbMouseChangeMoveRatio: New ratio 96x96
> Sync: GraphicsHeap Size 8388608
> Sync: Pentium Pro polygon rendering on
> Sync: setup_game: Speech recognition disabled: KeeperSpeech module not found
> LbDataFree: freeing "data/pointer64.dat"...done
> LbDataFree: freeing "data/pointer64.tab"...done
> Sync: LbScreenSetup: Mode 2560x1440x32 setup succeeded
> Sync: LbMouseChangeMoveRatio: New ratio 768x768
> Sync: get_startup_menu_state: Standard startup state selected
> Sync: Frontend state change from 0 into 1
> Sync: Created menu ID 18 at slot 0, pos (320,0) size (1920,1440)
> Sync: Frontend state change from 1 into 27
> Sync: Created menu ID 39 at slot 0, pos (320,0) size (1920,1440)
> Sync: Frontend state change from 27 into 1
> Sync: Created menu ID 18 at slot 0, pos (320,0) size (1920,1440)
> Sync: Frontend state change from 1 into 30
> Sync: Created menu ID 40 at slot 0, pos (320,0) size (1920,1440)
> Sync: Frontend state change from 30 into 7
> Sync: Frontend state change from 7 into 0
> LbDataFree: freeing "ldata/frontft1.dat"...done
> LbDataFree: freeing "ldata/frontft1.tab"...done
> LbDataFree: freeing "ldata/frontft2.dat"...done
> LbDataFree: freeing "ldata/frontft2.tab"...done
> LbDataFree: freeing "ldata/frontft3.dat"...done
> LbDataFree: freeing "ldata/frontft3.tab"...done
> LbDataFree: freeing "ldata/frontft4.dat"...done
> LbDataFree: freeing "ldata/frontft4.tab"...done
> LbDataFree: freeing "*FE_BACKUP_PAL"...done
> Sync: LbScreenSetup: Mode 2560x1440x32 setup succeeded
> Sync: LbMouseChangeMoveRatio: New ratio 768x768
> Sync: GraphicsHeap Size 8388608
> Sync: reenter_video_mode: Switched video to 2560x1440x32 (mode 28)
> Script(line 15): script_add_command: Level files version 1.
> Sync: Optional file "map00083.flg" doesn't exist or is too small.
> Sync: Created menu ID 1 at slot 0, pos (0,0) size (499,1425)
> Sync: Created menu ID 2 at slot 1, pos (0,0) size (499,1425)
> load_script: Used script resources: 0/16 tunneller triggers, 0/48 party triggers, 6/64 script values, 7/48 IF conditions, 0/16 party definitions
> Error: Attempt to write to inaccessible memory address.
>   in keeperfx.dll at 0023:02d60607, base 029d0000
>   in KERNELBASE.dll at 0023:76ef30f6, base 76de0000
>   in [unknown module] at 0023:0094ffcc, base 00000000
>   in KERNELBASE.dll at 0023:76ef17e3, base 76de0000
>   in keeperfx.exe at 0023:004378b3, base 00400000
>   in keeperfx.exe at 0023:00420b89, base 00400000
>   in keeperfx.exe at 0023:0041fcd0, base 00400000
>   in keeperfx.exe at 0023:004441d5, base 00400000
>   in keeperfx.exe at 0023:004af0d7, base 00400000

EDIT: 
I fixed the problem by deleting the settings.dat file in my Keeperfx/save directory

**Comment by Loobinex** [comment]
Good that you've manage to solve it. I don't know what happened to cause it.  (Unless you modified your own game and edited your floating_spirit).

I'll close this issue now, and hope this was a one-time fluke. Thank you for reporting though, when it happens again please tell me and I'll reopen the issue.

**Comment by Ccursed** [comment]
I did not modify the game, apart from inserting my resolutions into the .cfg file and checking the no intro and no sound tickmarks in the settings via launcher.
