### ISSUE TITLE
Screen flickering while possessing creature in high screen resolution

### ISSUE THREAD

**Issue by Loobinex** [Loobinex/keeperfx-unofficial#137]
If you possess a unit and walk through water, you get an annoying screen flicker. This has not always been there, and I don't know when it was introduced yet.

See image:
![image](https://user-images.githubusercontent.com/13840686/76693254-5cebb200-6662-11ea-9880-525ba90a41a4.png)

**Comment by Loobinex** [comment]
At least as far back as unofficial 1910, can also be easily reproduced by starting lvl10 and walking through snow:
![image](https://user-images.githubusercontent.com/13840686/76693305-19457800-6663-11ea-9771-cdc0f7d55efb.png)

**Comment by Loobinex** [comment]
Well, it seems to be there in 0.4.5.1228 as well, just a bit harder to reproduce:
![image](https://user-images.githubusercontent.com/13840686/76693337-8f49df00-6663-11ea-90b2-50c335de9d05.png)

**Comment by Loobinex** [comment]
Found the cause, it's not version related, but screen resolution related. In low resolutions this is hardly an issue, but in 1920x1080x32 this is really annoying.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
I recommend using a slightly lower higher resolution such as 1280x720 which is much more stable.  I wasn't able to get the game running properly in 1K full HD

**Comment by Loobinex** [comment]
Issue moved to official project.
