### ISSUE TITLE
Bridge icon disappears from build menu

### ISSUE THREAD

**Issue by G-Paris** [Loobinex/keeperfx-unofficial#145]
Noticed in multiple normal campaign levels, timing of the disappearance differs between starting research at the start of the level, or nearly finishing all research.

Speculation: might have something to do with an AI-player building/researching bridge?

Could not find anything apparent in heavy log-file.

Second screenshot is a couple of seconds after the first.
![with_bridge](https://user-images.githubusercontent.com/24733193/79121440-9b75a900-7d95-11ea-83b3-d022adaeb07e.png)
![without-bridge](https://user-images.githubusercontent.com/24733193/79121441-9ca6d600-7d95-11ea-9d33-c39ceaca8335.png)

Heavy log file, period of loading save just before and quitting after bridge disappears.
[keeperfx.log](https://github.com/Loobinex/keeperfx-unofficial/files/4469525/keeperfx.log)

Savegame just before bridge dissapears
[fx1g0007 (1).zip](https://github.com/Loobinex/keeperfx-unofficial/files/4469526/fx1g0007.1.zip)

**Comment by Loobinex** [comment]
Are you playing New Game+? If so, on some levels it's by design that the bridge is disappearing. That means you failed the conditions to get the transfer-creature special.
You can see the twinkle on the interface the moment the thing happened that made you lose it.

**Comment by Loobinex** [comment]
I checked, that is exactly it. On this particular level, you lose the bridge when the first hero dies. 

And please allow me to give you a little hint: please consider room efficiency. When you have such low room efficiency as you have in your saved game, everything takes much longer, causing you to run out of gold and the computers to grow stronger than you do. To get higher room efficiency, make sure the rooms have reinforced walls all around and a door in the opening.

https://dungeonkeeper.fandom.com/wiki/Room_Flags#Efficiency

**Comment by G-Paris** [comment]
Thanks for the quick reply. After spending some time googling around I couldn't find any documentation about this happening, so I assumed it was a bug, guess it's a feature to give you the incentive to move quicker. :)

Does make the game pretty hard, as it becomes more difficult to move quick if you missed the transfer creature special for the same reason in the last game.

Do you have a link with more info about the New game+ campaign or other KeeperFX unofficial features?

Thanks for the tips about room efficiency and especial for spending the time one devving KeeperFX, I'm thoroughly enjoying replaying this nostalgic classic!

**Comment by Loobinex** [comment]
Yes, New Game+ is a bit more challenging than the original campaign. If it's too much for you, try the original some more. Or, you could also come to the [discord](https://discord.gg/zKTjfDh), and ask for some tips to play there.

As for info on New Game+, look [here](https://keeperklan.com/threads/4860-Campaign-New-game-plus).
KeeperFX Unofficial, well, look [here](https://keeperklan.com/threads/7104-KeeperFX-Unofficial-0-4-7), [here](https://keeperklan.com/threads/5174-KeeperFX-Unofficial-0-4-6) and [here](https://keeperklan.com/threads/6928).
