### ISSUE TITLE
Diggers gain experience by working

### ISSUE THREAD

**Issue by CarlGustavAlbertDwarfsteinYung** [Loobinex/keeperfx-unofficial#146]
In my local repo I made my diggers gain passive experience when digging, dropping a carried object, fortifying and converting at 300 XP per action which amounts to 3 levels every 5-10 minutes. 

This is a feature that DK2 has and most DK clones have as you know.
I have also added the function to upgrade level if the experience is enough for next level. 

Is this something DK1/KeeperFX users would want?

**Comment by Loobinex** [comment]
By default, I would say no, as it throws the current game out of balance. As an option for people to mod into their own games, or for mapmaker to enable in their custom campaigns, that would be great.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Yes I also agree as an optional setting not by default.

**Comment by Loobinex** [comment]
Well, share the code,...

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Of course. These are my local changes. https://github.com/CarlGustavAlbertDwarfsteinYung/keeperfx-unofficial/commit/ee6e9a39373d357b789164b9bd990ab605af6bc5#diff-0bd97f461a003eca7642473028760af6

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
Seems I have forgotten a few check level upgrades . Anyway , there is an issue with pretty path not giving any experience.

**Comment by Loobinex** [comment]
Thanks. I'll look at it tonight. Be sure to join the keeperklan discord: https://discord.gg/zKTjfDh
