### ISSUE TITLE
some files in Levels\ and most in levels\

### ISSUE THREAD

**Issue by Ziusudra** [Loobinex/keeperfx-unofficial#152]
This is only a problem when running in Wine as Linux thinks those are different directories. So the levels with files in Levels\ don't work as the game is using levels\\. Moving the files in Levels to levels makes them work. This with the build 1913 release.

 Other than that it runs perfectly in Wine.

**Comment by Loobinex** [comment]
Could you please provide a bit more information?

**Comment by Ziusudra** [comment]
Working on it. (Why the hell does hitting enter in the subject submit the issue, github?)

**Comment by Ziusudra** [comment]
Other than that it runs perfectly in Wine.

**Comment by Loobinex** [comment]
Thank you for reporting. However, somebody already let me know. The [alpha builds](https://keeperklan.com/threads/6928) already come with everything in \levels\, and the next full version will also come without anything in \Levels\
