### ISSUE TITLE
 Launcher:Settings Editor - UI Bug #1

### ISSUE THREAD

**Issue by eddebaby** [Loobinex/keeperfx-unofficial#170]
Setting the Movie Resolution to 320x200x32 in the Settings Editor will change the drop-down for the **Menu Resolution** to 320x200x32 on next launch of the Settings Editor (toggling Windowed Mode also seems to trigger the change). This is not saved until you can see the value of the drop-down change, so it is triggered on "init" of the drop-downs, not changing of the Movie Resolution drop-down.

**Comment by Loobinex** [comment]
Fixed in https://github.com/dkfans/keeperfx-launcherwx/commit/4899cb5a8776a96c9849387fb75fd62995a9f0a1
