### ISSUE TITLE
Toggling the 1st person menu only works correctly on the 1st page

### ISSUE THREAD

**Issue by eddebaby** [Loobinex/keeperfx-unofficial#173]
If you toggle off the 1st person menu whilst viewing any page but the first one, the items on the page will not be hidden with the rest of the menu.

![1stperson_menubug](https://user-images.githubusercontent.com/1984342/88748315-a0921480-d148-11ea-9352-339afca4540b.png)

**Comment by Loobinex** [comment]
I can reproduce the issue. Not only do they not turn off, but when I do get to turn them off they don't turn back on again.
I tried fixing it by adding Query 3 and 4 to toggle_first_person_menu, but while I could get Query3 to turn off like that, Query4 stayed on.

**Comment by Loobinex** [comment]
I did figure it out after all.
