### ISSUE TITLE
Creatures duplicate on map screen

### ISSUE THREAD

**Issue by Loobinex** [Loobinex/keeperfx-unofficial#2]
In r1825 there are more creatures visible on the map than there are actually present in the level. This bug is not present in the official 0.4.6.1821.

![tunnelersonmap](https://cloud.githubusercontent.com/assets/13840686/19619573/cb47a192-986a-11e6-9a6c-4ed48ea308db.png)
Save game attached.: ![fx1g0007.zip](https://cloud.githubusercontent.com/assets/13840686/19619575/d5010f0c-986a-11e6-9091-eeeaf9e55cc0.jpg)

**Comment by Loobinex** [comment]
I've investigated the issue. It has not been newly introduced in the unofficial branch, but was present in official 0.4.6.1793, the version where I split of the branch. r1814 still had the bug, r1815 (git 77af1e4) has it fixed.

**Comment by spartahawk** [comment]
I'll have a look at this as soon as I can familiarize myself with everything involved!

**Comment by spartahawk** [comment]
Any tips for finding the associated commit to  0.4.6.1821 that doesn't have the bug? Are all of those still on Google Code (even if read-only)? If so I could match the dates...

**Comment by Loobinex** [comment]
Good.
And yes, like mentioned, on [this page](http://keeper.lubiki.pl/html/dk_keeperfx_nighold.php?branch=stable)you can find all version numbers next to the git-numbers. So simply pressing Ctrl+F on that page and typing 1815 would have gotten you that commit.

**Comment by spartahawk** [comment]
Yeah, sorry shortly after I wrote that, I remembered you shared that before via email. Thanks again.

**Comment by spartahawk** [comment]
That saved game attached is a dead link or something.

I'm unable to reproduce this issue so far. On the original campaign level 11, none of the heroes that appear causes this issue in the map screen.

Does it only happen for creatures that existed from the beginning of the level. I'm going to try that now.

**Comment by Loobinex** [comment]
Steps to reproduce:
1) Run level 17 with the -alex command line option
2) Access the cheat menu to display the full map
3) Frameskip to the point where the parties spawn and have walked around for a bit
4) Look on the map and see the tunnelers show up lots of times.

Attached a package file and save game with the issue present.
[fx1g0007.zip](https://github.com/Loobinex/keeperfx-unofficial/files/1666022/fx1g0007.zip)
[packet.zip](https://github.com/Loobinex/keeperfx-unofficial/files/1666023/packet.zip)

**Comment by spartahawk** [comment]
Still not seeing it on lvl 17 with all the tunnelers and full map displayed. I let them go for quite a while but I'll let them run around longer. Still, if it's not known exactly when it occurs (there might be something particular, unrelated, that triggers it), I can try apply the changes and attempt to fix the code conflicts.

**Comment by spartahawk** [comment]
Okay I'll look at the saved game (although I'm not able to get it so far from scratch on my own computer so far).

**Comment by spartahawk** [comment]
Aha okay I'm seeing it in your packet game.

**Comment by spartahawk** [comment]
And I'm seeing it on mine from fresh too. Alright. I'll get to it.

**Comment by spartahawk** [comment]
If you want to try out a multiplayer session I'm up for that.

**Comment by Loobinex** [comment]
Fixed in  f65d89f
