### ISSUE TITLE
Expand EXPORT_VARIABLE command with  timer/flag/creature/room/trap/door

### ISSUE THREAD

**Issue by Loobinex** [Loobinex/keeperfx-unofficial#47]
The EXPORT_VARIABLE command can export a variable to a campaign_flag to use on the next level. However, at the moment it only works with the special variables like MONEY and BATTLES_WON.

The IF statement that compares a variable with a number, supports those, and in addition also the timer, flag, creature, room, trap, door and campaign_flag type variables.

We could expand the EXPORT_VARIABLE command to include these other types of variables as well.
- Creatures are most useful to have,
- room, trap, door will probably not be used as much, but are pretty straightforward to include I assume
- timers could also be useful, a mapmaker might want to design maps based on the speed a player accomplishes tasks
- flags are technically pointless. If you want to export a flag to a campaign_flag, you could have used a campaign_flag in the first place. The only reason to add this, would be to be able to say 'all variables can be exported'.
- campaign_flags I would probably go so far as to exclude here, because you'd be exporting them to themselves. There's no reason at all to do this in the script, so for me the only reason to allow this, is if it would be easier than when we would disallow it.

**Comment by OrsonMaxwell** [comment]
I agree with all points, but I'd leave the usual FLAGs exportable - just for kicks. It is indeed pretty straightforward to implement taking IF as a model.
I'm already working on this.

**Comment by OrsonMaxwell** [comment]
I believe this can be closed as fixed by https://github.com/Loobinex/keeperfx-unofficial/commit/db9f0875182cd46e3522d13a0bf9265bc7ab1dab
